construct message as Vec<u8> instead of (loussy) string
running 1 test
test eval::tests::eval_file_error_invalid_path ... FAILED

failures:

---- eval::tests::eval_file_error_invalid_path stdout ----
thread 'eval::tests::eval_file_error_invalid_path' panicked at 'assertion failed: `(left == right)`
  left: `"ruby: file not found in virtual file system -- not/valid/utf8/�.rb"`,
 right: `"ruby: file not found in virtual file system -- [110, 111, 116, 47, 118, 97, 108, 105, 100, 47, 117, 116, 102, 56, 47, 255, 46, 114, 98]"`', artichoke-backend/src/eval.rs:257:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

failures:
    eval::tests::eval_file_error_invalid_path

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 291 filtered out; finished in 0.07s