Use to_str().unwrap() instead of to_string_loussy() for path in error message
running 1 test
test eval::tests::eval_file_error_invalid_path ... FAILED

failures:

---- eval::tests::eval_file_error_invalid_path stdout ----
thread 'eval::tests::eval_file_error_invalid_path' panicked at 'called `Option::unwrap()` on a `None` value', artichoke-backend/src/eval.rs:63:96
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

failures:
    eval::tests::eval_file_error_invalid_path

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 291 filtered out; finished in 0.06s